title: mcmicro
description: Multiple-choice microscopy pipeline

remote_theme: pmarsceill/just-the-docs
color_scheme: lsp
search_enabled: true
heading_anchors: true


# Aux links for the upper right navigation
aux_links:
  "mcmicro on GitHub":
    - "//github.com/labsyspharm/mcmicro"
aux_links_new_tab: false


# Footer content
# appears at the bottom of every page's main content

back_to_top: true
back_to_top_text: "Back to top"

footer_content: "&copy; 2020 Laboratory of Systems Pharmacology. Distributed by an <a href=\"\">MIT license.</a>"

last_edit_timestamp: true
last_edit_time_format: "%b %e %Y" # format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html


# Google Analytics 
# FIXME this is copied from cycif.org
# ga_tracking: UA-41775478-2
ga_tracking_anonymize_ip: true # Use GDPR compliant Google Analytics settings


plugins:
  - jekyll-seo-tag


repository: labsyspharm/mcmicro


exclude: ["node_modules/", "*.gemspec", "*.gem", "Gemfile", "Gemfile.lock", "package.json", "package-lock.json",  "script/", "LICENSE.txt", "lib/", "bin/", "README.md", "Rakefile"]
compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false